Notícias favoritas
therewasaproblem/whispr pull request #38
Opened 2019-11-06 01:56 UTC by guigonzalo

Tive que dar uma arrumada no banco pros padrões do rails que pede que as tabelas que vão ter uma associação precisam estar em ordem alfabética tipo news_user em vez de user_news.
Faltam os testes e não teve javascript dessa vez ainda :pensive:

2019-11-06 11:50 UTC, ekisu requested changes
Só a parte da migração precisa mudar mesmo, o resto é nitpicking.

2019-11-06 11:50 UTC, ekisu commented on app/controllers/favorites_controller.rb
> +        if @user.news.where(:id=>id).present?
Usar `@user.news.exists?(id)` é mais claro, acho.

2019-11-06 11:50 UTC, ekisu commented on app/controllers/favorites_controller.rb
> +        if @user.news.where(:id=>id).blank?
Igual aqui.

2019-11-06 11:50 UTC, ekisu commented on db/migrate/20191022005845_fixing_associations.rb
> +    create_table :categories_users do |t|
Isso provavelmente vai conflitar com o que o Kelvin fez, além disso isso devia ser uma migração nova (dropar as tabelas antigas e criar as novas), e não editar essa migração.

2019-11-06 11:50 UTC, ekisu commented on app/views/favorites/_favorites_card.html.erb
> +<div class="card border-light mb-3">
Esse arquivo ficou bem similar ao `_news_card`, talvez fosse melhor só adicionar a lógica de remover os favoritos nele mesmo.

2019-11-07 00:53 UTC, jimaeda approved these changes

2019-11-07 01:35 UTC, ekisu approved these changes
Pepino verde 👍

2019-11-14 01:02 UTC, merged